# Generated by Django 5.0.1 on 2025-10-05 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '__first__'),
        ('members', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='csv_imports/')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(blank=True, max_length=100)),
                ('rows_processed', models.IntegerField(default=0)),
                ('rows_created', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'CSV Import',
                'verbose_name_plural': 'CSV Imports',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('total_attendees', models.IntegerField(blank=True, null=True)),
                ('waiting_list', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('modified_by', models.CharField(blank=True, max_length=100)),
                ('import_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.member')),
                ('session_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usages', to='cards.sessioncard')),
            ],
            options={
                'verbose_name': 'Sessie Aanwezigheid',
                'verbose_name_plural': 'Sessie Aanwezigheden',
                'ordering': ['-session_date'],
                'unique_together': {('member', 'session_date', 'title')},
            },
        ),
    ]
