# Generated by Django 5.0.1 on 2025-10-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionattendance',
            name='card_session_used',
            field=models.BooleanField(default=False, help_text='Indicates if this session consumed a session from the card'),
        ),
    ]
