# Generated by Django 5.0.1 on 2026-01-26 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_add_session_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionschedule',
            name='max_capacity',
        ),
        migrations.RemoveField(
            model_name='sessionschedule',
            name='size_category',
        ),
        migrations.AddField(
            model_name='sessionattendance',
            name='size_category',
            field=models.CharField(blank=True, choices=[('S', 'Small (32-36)'), ('M', 'Medium (37-41)'), ('L', 'Large (42-46)'), ('XL', 'Extra Large (47+)')], help_text='Schoenmaat categorie voor deze boeking', max_length=5, null=True),
        ),
        migrations.CreateModel(
            name='SessionSizeCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_category', models.CharField(choices=[('S', 'Small (32-36)'), ('M', 'Medium (37-41)'), ('L', 'Large (42-46)'), ('XL', 'Extra Large (47+)')], help_text='Schoenmaat categorie', max_length=5)),
                ('capacity', models.IntegerField(default=0, help_text='Aantal beschikbare schoenen voor deze maat', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_capacities', to='bookings.sessionschedule')),
            ],
            options={
                'verbose_name': 'Maat Capaciteit',
                'verbose_name_plural': 'Maat Capaciteiten',
                'ordering': ['size_category'],
                'unique_together': {('session', 'size_category')},
            },
        ),
    ]
