# Generated by Django 5.0.1 on 2026-01-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_sessionschedule_max_capacity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionSizeCapacity',
        ),
    ]
