# Generated by Django 5.0.1 on 2026-01-27 21:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_delete_sessionsizecapacity'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(default='Deinze Kouter 93', max_length=200)),
                ('event_datetime', models.DateTimeField(help_text='Datum en tijd van het evenement')),
                ('duration_minutes', models.IntegerField(default=60, help_text='Duur in minuten', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)])),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_capacity', models.IntegerField(blank=True, help_text='Maximaal aantal deelnemers (leeg = gebaseerd op apparatuur)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True, help_text='Is dit evenement nog open voor boekingen')),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bedrijfsevenement',
                'verbose_name_plural': 'Bedrijfsevenementen',
                'ordering': ['-event_datetime'],
            },
        ),
        migrations.CreateModel(
            name='BusinessEventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('shoe_size', models.CharField(max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('size_category', models.CharField(blank=True, choices=[('S', 'Small (32-36)'), ('M', 'Medium (37-41)'), ('L', 'Large (42-46)'), ('XL', 'Extra Large (47+)')], max_length=5)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bookings', to='bookings.businessevent')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_event_bookings', to='members.member')),
            ],
            options={
                'verbose_name': 'Evenement Boeking',
                'verbose_name_plural': 'Evenement Boekingen',
                'ordering': ['-booked_at'],
                'unique_together': {('event', 'email')},
            },
        ),
    ]
