# Generated by Django 5.2.10 on 2026-01-29 19:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_businessevent_businesseventbooking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Bedrijfsnaam")),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Contact E-mail"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Contact Telefoon"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "allow_multiple_bookings",
                    models.BooleanField(
                        default=False,
                        help_text="Als aangevinkt mogen gebruikers zich voor meerdere events van dit bedrijf inschrijven",
                        verbose_name="Meerdere inschrijvingen toestaan",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Opmerkingen")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actief")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bedrijf",
                "verbose_name_plural": "Bedrijven",
                "ordering": ["name"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="businesseventbooking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="businessevent",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Optioneel: koppel aan een bedrijf voor meerdere events onder één link",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="bookings.company",
                verbose_name="Bedrijf",
            ),
        ),
    ]
