version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kangoo
      - POSTGRES_USER=kangoo
      - POSTGRES_PASSWORD=kangoo_dev_password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kangoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://kangoo:kangoo_dev_password@db:5432/kangoo
      - DEBUG=True
      - SECRET_KEY=dev-secret-key-change-in-production
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  media_volume: