version: '3.8'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=kangoo
      - POSTGRES_USER=kangoo
      - POSTGRES_PASSWORD=${DB_PASSWORD}  # Use environment variable
    ports:
      - "5432:5432"
    restart: unless-stopped  # Auto-restart on failure
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kangoo"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - ./media:/app/media  # Store media files locally
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://kangoo:${DB_PASSWORD}@db:5432/kangoo
      - DEBUG=False  # IMPORTANT: Set to False in production
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped