# Generated by Django 5.0.1 on 2025-10-05 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment_id', models.CharField(help_text='Unieke ID voor dit stuk apparatuur', max_length=50, unique=True)),
                ('size', models.CharField(choices=[('S', 'Small (32-36)'), ('M', 'Medium (37-41)'), ('L', 'Large (42-46)'), ('XL', 'Extra Large (47+)')], max_length=5)),
                ('status', models.CharField(choices=[('available', 'Beschikbaar'), ('in_use', 'In Gebruik'), ('maintenance', 'Onderhoud'), ('broken', 'Defect')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('next_maintenance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apparatuur',
                'verbose_name_plural': 'Apparatuur',
                'ordering': ['size', 'equipment_id'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Onderhoudslogboek',
                'verbose_name_plural': 'Onderhoudslogboeken',
                'ordering': ['-date'],
            },
        ),
    ]
