# Generated by Django 5.2.10 on 2026-01-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0002_add_spring_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShellType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Naam"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschrijving"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actief")),
            ],
            options={
                "verbose_name": "Soort Schelp",
                "verbose_name_plural": "Soorten Schelpen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SpringType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Naam"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschrijving"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actief")),
            ],
            options={
                "verbose_name": "Soort Veer",
                "verbose_name_plural": "Soorten Veren",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="equipment",
            name="spring_type",
            field=models.CharField(
                choices=[("standard", "Standaard"), ("hd", "HD")],
                default="standard",
                max_length=20,
                verbose_name="Soort Veer (basis)",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="shell_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Type schelp van de schoen",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipment.shelltype",
                verbose_name="Soort Schelp",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="spring_type_detail",
            field=models.ForeignKey(
                blank=True,
                help_text="Gedetailleerd veertype (beheerd door admin)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="equipment.springtype",
                verbose_name="Soort Veer",
            ),
        ),
    ]
