# Generated by Django 5.2.10 on 2026-01-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="date_of_birth",
            field=models.DateField(
                blank=True,
                help_text="Vereist voor verzekering",
                null=True,
                verbose_name="Geboortedatum",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="insurance_status",
            field=models.CharField(
                choices=[
                    ("none", "Niet aangevraagd"),
                    ("requested", "Aangevraagd"),
                    ("processing", "In verwerking"),
                    ("approved", "In orde"),
                    ("refused", "Geweigerd (wil geen verzekering)"),
                ],
                default="none",
                help_text="Status van de verzekering voor dit lid",
                max_length=20,
                verbose_name="Verzekeringsstatus",
            ),
        ),
    ]
