# Generated by Django 5.0.1 on 2025-10-05 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(default='10-Sessie Kaart', max_length=50)),
                ('total_sessions', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('sessions_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('purchased_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Actief'), ('expired', 'Verlopen'), ('completed', 'Volledig Gebruikt')], default='active', max_length=20)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_cards', to='members.member')),
            ],
            options={
                'verbose_name': 'Sessiekaart',
                'verbose_name_plural': 'Sessiekaarten',
                'ordering': ['-purchased_date'],
            },
        ),
    ]
