# Generated by Django 5.2.10 on 2026-01-29 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_add_trial_support"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Bijv. 1 Beurt, 5 Beurten, 10 Beurten",
                        max_length=100,
                        verbose_name="Naam",
                    ),
                ),
                (
                    "sessions",
                    models.IntegerField(
                        help_text="Hoeveel beurten zitten er in deze kaart",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Aantal Beurten",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Prijs in euro",
                        max_digits=6,
                        verbose_name="Prijs",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("regular", "Normale Kaart"), ("trial", "Oefenbeurt")],
                        default="regular",
                        max_length=20,
                        verbose_name="Categorie",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actief")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="Sorteervolgorde"),
                ),
            ],
            options={
                "verbose_name": "Kaartsoort",
                "verbose_name_plural": "Kaartsoorten",
                "ordering": ["sort_order", "sessions"],
            },
        ),
        migrations.AddField(
            model_name="sessioncard",
            name="card_type_ref",
            field=models.ForeignKey(
                blank=True,
                help_text="Verwijzing naar de kaartsoort (optioneel)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cards.cardtype",
                verbose_name="Kaartsoort",
            ),
        ),
    ]
